### ISSUE TITLE
Bug in top gene selection?

### ISSUE THREAD

**Issue by buske** [phenotips/remote-matching#16]
For some reason, the top gene included for matchmaking from F0000010 is ATP6V0A4, rather than SRCAP, which actually has a higher score in the exomiser-annotated VCF file. ATP6V0A4 is the second-highest.

**Comment by allasm** [comment]
I will also double-check how top genes are selected (current code gets the list of all genes and computes all scores and picks top N outside of exomiser)

**Comment by buske** [comment]
Yeah, I took a look at that code and couldn't find any obvious issue. Could be a problem with patient-network, but the gene does show up correctly in internal patient matching.

**Comment by buske** [comment]
Found the bug. It's actually returning the ***last*** (lowest-ranked) gene in the file, due to ascending rather than descending sort order. It's just the second and last gene names were similar.
