### ISSUE TITLE
Not all match results are being shown

### ISSUE THREAD

**Issue by buske** [phenotips/remote-matching#29]
For example, for https://phenomecentral.org/P0000277, there are 2 hits in GeneMatcher, but only one is visualized in the UI.

**Comment by allasm** [comment]
Hmm, I did a new request to check, and there seem to be only one match returned by GeneMatcher:

2015-08-04 15:30:45,692 ... DefaultRemoteMatchingService - Sending matching request to [https://genematcher.org/mmapi/match]: {"patient":{"id":"P0000277", ...} 

2015-08-04 15:31:08,038 ... Reply to matching request: STATUS: [200], DATA: [{
    "_disclaimer": "People proposing to publish material that makes use of matches achieved through the GeneMatcher database agree to: Acknowledge GeneMatcher and the grant that supports it: 1U54HG006542; and Notify the systems administrator of a published paper (so that we can track our results), by sending an email through the 'Contact Us' tab on GeneMatcher. No one is authorized to attempt to identify patients whose results are in GeneMatcher by any means. This applies to matches made within GeneMatcher or with any other database included in the Matchmaker Exchange. GeneMatcher provides these data in good faith as a research tool, but without verifying the accuracy, clinical validity or utility of the data. GeneMatcher. Johns Hopkins University makes no warranty, express or implied, nor assumes any legal liability or responsibility for any purpose for which the data are used.", 
    "results": [
        {
            "patient": {
                ...
                "id": "71", 
                ...
            }, 
            ...
        }
    ]
}]
